version: "3"

services:
  roscore:
    image: realm_gc:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: roscore

  vicon_bridge:
    image: realm_gc:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - roscore
    command: /bin/bash -c '. /catkin_ws/devel/setup.bash && roslaunch --wait vicon_bridge vicon.launch datastream_hostport:=192.168.0.9'

  rviz:
    image: realm_gc:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - roscore
    command: /bin/bash -c '. /catkin_ws/devel/setup.bash && rviz'

  bash:
    image: realm_gc:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - DISPLAY=${DISPLAY} # allows GUI access
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # allows GUI access
      - ./realm_gc:/catkin_ws/src/realm_gc # allows access to the ROS package in the realm directory
    network_mode: host # allows access to the host's network (and the robot)
    privileged: true # needed for GUI + USB access
    stdin_open: true # allows you to attach to a shell in this container
    tty: true # allows you to attach to a shell in this container
    command: bash
