!!python/object:argparse.Namespace
algo: gcbf+
alpha: 1.0
area_size: 2.5
buffer_size: 512
debug: false
dim_factor: 2
env: DubinsCarAdapt
eval_epi: 1
eval_interval: 1
gnn_layers: 1
horizon: 32
log_dir: ./logs
loss_action_coef: 1.0e-06
loss_h_dot_coef: 0.01
loss_safe_coef: 1.0
loss_unsafe_coef: 1.0
lr_actor: 2.0e-05
lr_cbf: 2.0e-05
mov_obs: 8
mov_obs_at_infty: false
mov_obs_speed: 0.01
n_env_test: 32
n_env_train: 12
n_rays: 32
name: null
node_feat: 5
num_agents: 4
obs: 4
prev_trained_model_path: null
save_interval: 100
seed: 1
station_obs_at_infty: false
steps: 1000
alpha: 1.0
batch_size: 256
eps: 0.02
gnn_layers: 1
horizon: 32
inner_epoch: 8
loss_action_coef: 1.0e-06
loss_h_dot_coef: 0.01
loss_safe_coef: 1.0
loss_unsafe_coef: 1.0
lr_actor: 2.0e-05
lr_cbf: 2.0e-05
max_grad_norm: 2.0
seed: 1
